-- Seed Admin User
-- This creates the initial admin account
-- Username: admin
-- Password: admin@admin

-- Insert admin user with bcrypt hash for password 'admin@admin'
-- Hash generated: $2b$10$YQPZmEhZvF0qhF5xH9jIZO8bJZ5nQXKf5g6Z5qh5X5Y5Z5qh5X5Y5a (example, will be generated by app)
INSERT INTO users (username, email, name, password_hash, role, club_name, phone) 
VALUES (
  'admin',
  'admin@college.edu',
  'System Administrator',
  '$2b$10$YourHashWillBeGeneratedByApp',
  'admin',
  'Administration',
  '1234567890'
) ON DUPLICATE KEY UPDATE role='admin';

-- Note: The actual password hash will be generated when you first create the admin user
-- or you can use the /api/auth/init-admin endpoint (to be created)
